# Generated by Django 4.1.7 on 2023-02-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
